package:
    name: pyaxiom
    version: "1.3.1"

source:
    path: ../

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record=record.txt
    entry_points:
        - binner=pyaxiom.netcdf.grids.binner:run

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - numpy
        - pytz
        - python-dateutil
        - netcdf4
        - pandas
        - pyncml
        - pynco  # [not win]
        - simplejson

test:
    imports:
        - pyaxiom
        - pyaxiom.netcdf
        - pyaxiom.netcdf.grids
        - pyaxiom.netcdf.sensors
        - pyaxiom.tests
    commands:
        - binner --help

about:
    home: https://github.com/axiom-data-science/pyaxiom
    license: MIT License
    summary: 'An ocean data toolkit developed and used by Axiom Data Science'
